name: Flutter CI

on:
  push:

jobs:
  test:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1

      # Get flutter dependencies.
      - run: flutter pub get

      # Run tests for our flutter project.
      - run: flutter test
